const emiterTypes = {
  CALIBRATE_START: 'CALIBRATE_START',
  CALIBRATE_SUCCESS: 'CALIBRATE_SUCCESS',
  CALIBRATE_FAILURE: 'CALIBRATE_FAILURE',
  CALIBRATE_ERROR: 'CALIBRATE_ERROR',
};

export default emiterTypes;