const userTypes = {
  SYNCHRONIZE_CURRENT_USER_DATA: 'SYNCHRONIZE_CURRENT_USER_DATA',
  SYNCHRONIZE_USERS_DATA: 'SYNCHRONIZE_USERS_DATA',

  FETCH_CURRENT_USER_START: 'FETCH_CURRENT_USER_START',
  FETCH_CURRENT_USER_SUCCESS: 'FETCH_CURRENT_USER_SUCCESS',
  FETCH_CURRENT_USER_FAILURE: 'FETCH_CURRENT_USER_FAILURE',

  CHECK_CURRENT_USER_AUTH_START: 'CHECK_CURRENT_USER_AUTH_START',
  CHECK_CURRENT_USER_AUTH_END: 'CHECK_CURRENT_USER_AUTH_END',
};

export default userTypes;